version: "3"  # optional since v1.27.0
services:
  test:
    image: revis/prod2
    container_name: revis-test
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run test
volumes:
  node_modules: