version: '3.3'

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment: 
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next 